#!/bin/bash
set -e

SHA=$(jq -r '.sha' mastodon_openapi.json)
curl --silent --show-error --location \
  "https://github.com/abraham/mastodon-openapi/raw/${SHA}/dist/schema.json" \
  --output packages/mastodon_generator/mastodon_openapi.json

cd packages/mastodon_generator

dart run build_runner clean
dart run build_runner build

cd ../..

dart format .

dart packages/mastodon_generator/lib/hacks.dart

cd packages/mastodon

dart run build_runner build

dart fix --apply --code=unused_import

cd ../..

dart format .
